

#
# This file is autogenerated during plugin_quickstart and overwritten during
# plugin_makedist. DO NOT CHANGE IT if you plan to use plugin_makedist to update 
# the distribution.
#

from setuptools import setup, find_packages

kwargs = {'author': 'Herb Schilling',
 'author_email': 'hschilling@nasa.gov',
 'classifiers': ['Intended Audience :: Science/Research',
                 'Topic :: Scientific/Engineering'],
 'description': 'A wrapper for the Ipopt optimization code',
 'download_url': '',
 'include_package_data': True,
 'install_requires': ['openmdao.main'],
 'keywords': ['openmdao'],
 'license': 'NASA Open Source Agreement (NOSA) Version 1.3',
 'maintainer': 'Herb Schilling',
 'maintainer_email': 'hschilling@nasa.gov',
 'name': 'ipoptdriver',
 'package_data': {'ipoptdriver': []},
 'package_dir': {'': 'src'},
 'packages': ['ipoptdriver'],
 'url': '',
 'version': '0.9',
 'zip_safe': False}


setup(**kwargs)

